# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- development

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  SERVERURL: $(SERVERURL)
  DATABASENAME: $(DATABASENAME)
  DBUSER: $(DBUSER)
  DBPASSWORD: $(DBPASSWORD)
  PBURL: $(URL)

steps:
- script: docker-compose up --scale chrome=4 -d
  displayName: docker-compose
#- bash: "export BROWSER=chrome && 
#  export SERVERURL=$(SERVERURL) && 
#  export DATABASENAME=$(DATABASENAME) && 
#  export DBUSER=$(DBUSER) && 
#  export DBPASSWORD=$(DBPASSWORD) && 
#  export PBURL=$(URL)"

- task: UseDotNet@2
  inputs:
    version: '2.2.x'
    packageType: runtime
- task: DotNetCoreCLI@2
  inputs:
    command: test
    projects: '**/src/*.sln'
    arguments: '-v n'
