# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  solution: 'src/'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: DockerCompose@0
  inputs:
    containerregistrytype: 'Azure Container Registry'
    azureSubscription: 'NHSAPP-BuyingCatalogue'
    azureContainerRegistry: '{"loginServer":"buyingcat01.azurecr.io", "id" : "/subscriptions/7b12a8a2-f06f-456f-b6f9-aa2d92e0b2ec/resourceGroups/BCadminrepo/providers/Microsoft.ContainerRegistry/registries/buyingcat01"}'
    dockerComposeFile: '**/docker-compose.yml'
    action: 'Run a Docker Compose command'
    dockerComposeCommand: 'up --scale chrome=4 -d'
    arguments: ''
  displayName: 'Stand up a local Selenium grid'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: '
    export BROWSER=chrome &&
    export HUBURL=http://localhost:4444/wd/hub &&
    export MPURL=https://test.pb-buyingcatalogue.com &&
    dotnet build $(solution) &&
    dotnet test $(solution) -v n'
  displayName: 'Run the tests'