# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- development

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  BROWSER: chrome

steps:
- task: UseDotNet@2
  displayName: 'Use DotNet Core 3.1'
  inputs:
    version: 3.x
    includePreviewVersions: false

- script: docker-compose up --scale chrome=4 -d
  displayName: Selenium Grid Setup

- task: DotNetCoreCLI@2
  displayName: Run Acceptance Tests
  inputs:
    command: 'test'
    projects: 'src/**/*.csproj'
    arguments: '-v n'